### ISSUE TITLE
urxvt ctrl-shift-C/V not copying and pasting

### ISSUE THREAD

**Issue by buckey206** [hnykda/tutos#3]
# First of all, Thank you!

Your arch and i3 tutorial was almost exactly what I was looking for! You write amazing documentation. Thank you so much for taking the time to write all of that up! 

Because you have helped me so much I thought I'd share the  this cool command line tool I stumbled on. It's written in python. It's called [thefuck](https://github.com/nvbn/thefuck) 

---
## The issue

I saw in your Xdefaults on lines 28-30 had a setting to enable it in urxvt, I coppied the whole file to use as a base for urxvt however, copying and pasting doesn't work, any ideas why? 
#### some bacground

Before I started using Arch, I would install xubuntu and then i3 alongside it. I have grown to love the Ctrl-Shift-C/V of the xfce-terminal. However I wanted something more resource friendly, I tried out st by suckless and that was to barren, with no scrollback support and very little documentation I got tired of fighting with my terminal. That's when I stumbled aross your readthedocs and looking at your config, that could make it work.

**Comment by hnykda** [comment]
Hello,

thanks for your recommendation.

Regarding the issue, I am afraid I can't help you. I have switched to `xfce4-terminal` and `parcellite`. Both are lightweight and sufficient for me. Don't regret the switch :D .

**Comment by buckey206** [comment]
awesome, thanks for the quick reply!
